export const icons = {
  heart: "/icons/love.png",
  match: "/icons/match.png",
  safe: "/icons/safe.png",
  star: "/icons/star.png",
  add: "/icons/add.png",
  quotation: "/icons/quotation.png",
  achievementBlack: "/icons/acheivement-black.svg",
  achievementWhite: "/icons/acheivement-white.svg",
  misionBlack: "/icons/our-mission-black.svg",
  missionWhite: "/icons/our-mission-white.svg",
  storyBlack: "/icons/our-story-black.svg",
  storyWhite: "/icons/our-story-white.svg",
  teamBlack: "/icons/team-black.svg",
  teamWhite: "/icons/team-white.svg",
  cultureBlack: "/icons/culture-black.svg",
  cultureWhite: "/icons/culture-white.svg",
  privacyBlack: "/icons/privacy-black.svg",
  privacyWhite: "/icons/privacy-white.svg",
  tcBlack: "/icons/tc-black.svg",
  tcWhite: "/icons/tc-white.svg",
  guideBlack: "/icons/guide-black.svg",
  guideWhite: "/icons/guide-white.svg",
  refundBlack: "/icons/refund-black.svg",
  refundWhite: "/icons/refund-white.svg",
  safetyBlack: "/icons/safety-black.svg",
  safetyWhite: "/icons/safety-white.svg",
};
